### ISSUE TITLE
ERROR on yarn test at the very first launch

### ISSUE THREAD

**Issue by gvespucci** [murphye/hybrid-react-angular-spring-boot-apps#1]
Hi Eric
I've just cloned the project and tried to execute

`~/hybrid-react-angular-spring-boot-apps/multi-module-app (master)
$ mvn clean install`

and I've receved the following error:

`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (test) on project frontend: Failed to run task: 'yarn test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]`

I expected this would have worked.
Am I doing something wrong?
Regards
Thank you

**Comment by parml** [comment]
@gvespucci I get the same error.
I commented out the test related configuration part for the `maven-frontend-plugin` section in `frontend/pom.xml` and I got the build to succeed. 
However, when running 
`mvn spring-boot:run` I don't get the React starter welcome page, I get the 404-equivalent from Spring boot (Whitelabel Error Page).

**Comment by gvespucci** [comment]
@iovuio I did the same exact thing. Got same exact results.

**Comment by gvespucci** [comment]
It's time to make this die, I guess. 🤷
